targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
      json_serializable|json_serializable:
        enabled: true
      riverpod_generator|riverpod_generator:
        enabled: true